---
changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking changes
      labels:
        - breaking-change
    - title: New features
      labels:
        - enhancement
    - title: Bugs
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Dependabot
      labels:
        - dependabot
    - title: Other changes
      labels:
        - "*"
